//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aluwa3.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Surname {
            get {
                return this.User_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_SurnameField, value) != true)) {
                    this.User_SurnameField = value;
                    this.RaisePropertyChanged("User_Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CartProduct_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Cart_Product[] Cart_ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Cart_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CartProduct_Total {
            get {
                return this.CartProduct_TotalField;
            }
            set {
                if ((this.CartProduct_TotalField.Equals(value) != true)) {
                    this.CartProduct_TotalField = value;
                    this.RaisePropertyChanged("CartProduct_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_Id {
            get {
                return this.Cart_IdField;
            }
            set {
                if ((this.Cart_IdField.Equals(value) != true)) {
                    this.Cart_IdField = value;
                    this.RaisePropertyChanged("Cart_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Cart_Product[] Cart_Products {
            get {
                return this.Cart_ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.Cart_ProductsField, value) != true)) {
                    this.Cart_ProductsField = value;
                    this.RaisePropertyChanged("Cart_Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cart_Total {
            get {
                return this.Cart_TotalField;
            }
            set {
                if ((this.Cart_TotalField.Equals(value) != true)) {
                    this.Cart_TotalField = value;
                    this.RaisePropertyChanged("Cart_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Order_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Order_Product[] Order_ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Order_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Order_Address {
            get {
                return this.Order_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_AddressField, value) != true)) {
                    this.Order_AddressField = value;
                    this.RaisePropertyChanged("Order_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Order_Date {
            get {
                return this.Order_DateField;
            }
            set {
                if ((this.Order_DateField.Equals(value) != true)) {
                    this.Order_DateField = value;
                    this.RaisePropertyChanged("Order_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_Id {
            get {
                return this.Order_IdField;
            }
            set {
                if ((this.Order_IdField.Equals(value) != true)) {
                    this.Order_IdField = value;
                    this.RaisePropertyChanged("Order_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Order_Product[] Order_Products {
            get {
                return this.Order_ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_ProductsField, value) != true)) {
                    this.Order_ProductsField = value;
                    this.RaisePropertyChanged("Order_Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Order_Total {
            get {
                return this.Order_TotalField;
            }
            set {
                if ((this.Order_TotalField.Equals(value) != true)) {
                    this.Order_TotalField = value;
                    this.RaisePropertyChanged("Order_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart_Product", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class Cart_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Cart CartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartProd_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartProd_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Cart Cart {
            get {
                return this.CartField;
            }
            set {
                if ((object.ReferenceEquals(this.CartField, value) != true)) {
                    this.CartField = value;
                    this.RaisePropertyChanged("Cart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartProd_Id {
            get {
                return this.CartProd_IdField;
            }
            set {
                if ((this.CartProd_IdField.Equals(value) != true)) {
                    this.CartProd_IdField = value;
                    this.RaisePropertyChanged("CartProd_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartProd_Quantity {
            get {
                return this.CartProd_QuantityField;
            }
            set {
                if ((this.CartProd_QuantityField.Equals(value) != true)) {
                    this.CartProd_QuantityField = value;
                    this.RaisePropertyChanged("CartProd_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_Id {
            get {
                return this.Cart_IdField;
            }
            set {
                if ((this.Cart_IdField.Equals(value) != true)) {
                    this.Cart_IdField = value;
                    this.RaisePropertyChanged("Cart_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_Id {
            get {
                return this.Prod_IdField;
            }
            set {
                if ((this.Prod_IdField.Equals(value) != true)) {
                    this.Prod_IdField = value;
                    this.RaisePropertyChanged("Prod_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Cart_Product[] Cart_ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnvironmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaintenaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Order_Product[] Order_ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prod_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prod_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Cart_Product[] Cart_Products {
            get {
                return this.Cart_ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.Cart_ProductsField, value) != true)) {
                    this.Cart_ProductsField = value;
                    this.RaisePropertyChanged("Cart_Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Environment {
            get {
                return this.EnvironmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvironmentField, value) != true)) {
                    this.EnvironmentField = value;
                    this.RaisePropertyChanged("Environment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maintenace {
            get {
                return this.MaintenaceField;
            }
            set {
                if ((object.ReferenceEquals(this.MaintenaceField, value) != true)) {
                    this.MaintenaceField = value;
                    this.RaisePropertyChanged("Maintenace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Order_Product[] Order_Products {
            get {
                return this.Order_ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_ProductsField, value) != true)) {
                    this.Order_ProductsField = value;
                    this.RaisePropertyChanged("Order_Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prod_Description {
            get {
                return this.Prod_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Prod_DescriptionField, value) != true)) {
                    this.Prod_DescriptionField = value;
                    this.RaisePropertyChanged("Prod_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_Id {
            get {
                return this.Prod_IdField;
            }
            set {
                if ((this.Prod_IdField.Equals(value) != true)) {
                    this.Prod_IdField = value;
                    this.RaisePropertyChanged("Prod_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prod_Name {
            get {
                return this.Prod_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prod_NameField, value) != true)) {
                    this.Prod_NameField = value;
                    this.RaisePropertyChanged("Prod_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order_Product", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class Order_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdProd_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProdPurchase_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Aluwa3.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdProd_Id {
            get {
                return this.OrdProd_IdField;
            }
            set {
                if ((this.OrdProd_IdField.Equals(value) != true)) {
                    this.OrdProd_IdField = value;
                    this.RaisePropertyChanged("OrdProd_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_Id {
            get {
                return this.Order_IdField;
            }
            set {
                if ((this.Order_IdField.Equals(value) != true)) {
                    this.Order_IdField = value;
                    this.RaisePropertyChanged("Order_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProdPurchase_Price {
            get {
                return this.ProdPurchase_PriceField;
            }
            set {
                if ((this.ProdPurchase_PriceField.Equals(value) != true)) {
                    this.ProdPurchase_PriceField = value;
                    this.RaisePropertyChanged("ProdPurchase_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_Id {
            get {
                return this.Prod_IdField;
            }
            set {
                if ((this.Prod_IdField.Equals(value) != true)) {
                    this.Prod_IdField = value;
                    this.RaisePropertyChanged("Prod_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aluwa3.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempCartProd", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class TempCartProd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartProduct_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartProduct_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartProduct_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CartProduct_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartProduct_QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartProduct_Id {
            get {
                return this.CartProduct_IdField;
            }
            set {
                if ((this.CartProduct_IdField.Equals(value) != true)) {
                    this.CartProduct_IdField = value;
                    this.RaisePropertyChanged("CartProduct_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartProduct_Image {
            get {
                return this.CartProduct_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.CartProduct_ImageField, value) != true)) {
                    this.CartProduct_ImageField = value;
                    this.RaisePropertyChanged("CartProduct_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartProduct_Name {
            get {
                return this.CartProduct_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.CartProduct_NameField, value) != true)) {
                    this.CartProduct_NameField = value;
                    this.RaisePropertyChanged("CartProduct_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CartProduct_Price {
            get {
                return this.CartProduct_PriceField;
            }
            set {
                if ((this.CartProduct_PriceField.Equals(value) != true)) {
                    this.CartProduct_PriceField = value;
                    this.RaisePropertyChanged("CartProduct_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartProduct_Quantity {
            get {
                return this.CartProduct_QuantityField;
            }
            set {
                if ((this.CartProduct_QuantityField.Equals(value) != true)) {
                    this.CartProduct_QuantityField = value;
                    this.RaisePropertyChanged("CartProduct_Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempProd", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class TempProd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_EnvironmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_MaintenanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Product_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Category {
            get {
                return this.Product_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_CategoryField, value) != true)) {
                    this.Product_CategoryField = value;
                    this.RaisePropertyChanged("Product_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Description {
            get {
                return this.Product_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_DescriptionField, value) != true)) {
                    this.Product_DescriptionField = value;
                    this.RaisePropertyChanged("Product_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Environment {
            get {
                return this.Product_EnvironmentField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_EnvironmentField, value) != true)) {
                    this.Product_EnvironmentField = value;
                    this.RaisePropertyChanged("Product_Environment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Image {
            get {
                return this.Product_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_ImageField, value) != true)) {
                    this.Product_ImageField = value;
                    this.RaisePropertyChanged("Product_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Maintenance {
            get {
                return this.Product_MaintenanceField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_MaintenanceField, value) != true)) {
                    this.Product_MaintenanceField = value;
                    this.RaisePropertyChanged("Product_Maintenance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Product_Price {
            get {
                return this.Product_PriceField;
            }
            set {
                if ((this.Product_PriceField.Equals(value) != true)) {
                    this.Product_PriceField = value;
                    this.RaisePropertyChanged("Product_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Province {
            get {
                return this.Product_ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_ProvinceField, value) != true)) {
                    this.Product_ProvinceField = value;
                    this.RaisePropertyChanged("Product_Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Stock {
            get {
                return this.Product_StockField;
            }
            set {
                if ((this.Product_StockField.Equals(value) != true)) {
                    this.Product_StockField = value;
                    this.RaisePropertyChanged("Product_Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempCart", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class TempCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempCartCust_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TempCartProd_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempCart_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TempCart_TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempCartCust_Id {
            get {
                return this.TempCartCust_IdField;
            }
            set {
                if ((this.TempCartCust_IdField.Equals(value) != true)) {
                    this.TempCartCust_IdField = value;
                    this.RaisePropertyChanged("TempCartCust_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TempCartProd_Total {
            get {
                return this.TempCartProd_TotalField;
            }
            set {
                if ((this.TempCartProd_TotalField.Equals(value) != true)) {
                    this.TempCartProd_TotalField = value;
                    this.RaisePropertyChanged("TempCartProd_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempCart_Id {
            get {
                return this.TempCart_IdField;
            }
            set {
                if ((this.TempCart_IdField.Equals(value) != true)) {
                    this.TempCart_IdField = value;
                    this.RaisePropertyChanged("TempCart_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TempCart_Total {
            get {
                return this.TempCart_TotalField;
            }
            set {
                if ((this.TempCart_TotalField.Equals(value) != true)) {
                    this.TempCart_TotalField = value;
                    this.RaisePropertyChanged("TempCart_Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempOrderProd", Namespace="http://schemas.datacontract.org/2004/07/Aluwa")]
    [System.SerializableAttribute()]
    public partial class TempOrderProd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempOrdProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TempOrdProdPurchase_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempOrdProd_OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempOrdProd_ProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TempOrdProd_QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempOrdProd {
            get {
                return this.TempOrdProdField;
            }
            set {
                if ((this.TempOrdProdField.Equals(value) != true)) {
                    this.TempOrdProdField = value;
                    this.RaisePropertyChanged("TempOrdProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TempOrdProdPurchase_Price {
            get {
                return this.TempOrdProdPurchase_PriceField;
            }
            set {
                if ((this.TempOrdProdPurchase_PriceField.Equals(value) != true)) {
                    this.TempOrdProdPurchase_PriceField = value;
                    this.RaisePropertyChanged("TempOrdProdPurchase_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempOrdProd_OrderId {
            get {
                return this.TempOrdProd_OrderIdField;
            }
            set {
                if ((this.TempOrdProd_OrderIdField.Equals(value) != true)) {
                    this.TempOrdProd_OrderIdField = value;
                    this.RaisePropertyChanged("TempOrdProd_OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempOrdProd_ProdId {
            get {
                return this.TempOrdProd_ProdIdField;
            }
            set {
                if ((this.TempOrdProd_ProdIdField.Equals(value) != true)) {
                    this.TempOrdProd_ProdIdField = value;
                    this.RaisePropertyChanged("TempOrdProd_ProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempOrdProd_Quantity {
            get {
                return this.TempOrdProd_QuantityField;
            }
            set {
                if ((this.TempOrdProd_QuantityField.Equals(value) != true)) {
                    this.TempOrdProd_QuantityField = value;
                    this.RaisePropertyChanged("TempOrdProd_Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        Aluwa3.ServiceReference1.User Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.User> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        bool Register(Aluwa3.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(Aluwa3.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomerId", ReplyAction="http://tempuri.org/IService1/getCustomerIdResponse")]
        int getCustomerId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomerId", ReplyAction="http://tempuri.org/IService1/getCustomerIdResponse")]
        System.Threading.Tasks.Task<int> getCustomerIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomer", ReplyAction="http://tempuri.org/IService1/getCustomerResponse")]
        Aluwa3.ServiceReference1.User getCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomer", ReplyAction="http://tempuri.org/IService1/getCustomerResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.User> getCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserType", ReplyAction="http://tempuri.org/IService1/GetUserTypeResponse")]
        string GetUserType(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserType", ReplyAction="http://tempuri.org/IService1/GetUserTypeResponse")]
        System.Threading.Tasks.Task<string> GetUserTypeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductByCategory", ReplyAction="http://tempuri.org/IService1/getProductByCategoryResponse")]
        Aluwa3.ServiceReference1.Product[] getProductByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductByCategory", ReplyAction="http://tempuri.org/IService1/getProductByCategoryResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> getProductByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getproductById", ReplyAction="http://tempuri.org/IService1/getproductByIdResponse")]
        Aluwa3.ServiceReference1.Product getproductById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getproductById", ReplyAction="http://tempuri.org/IService1/getproductByIdResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product> getproductByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        Aluwa3.ServiceReference1.Product[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsById", ReplyAction="http://tempuri.org/IService1/GetProductsByIdResponse")]
        Aluwa3.ServiceReference1.Product[] GetProductsById(int[] productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsById", ReplyAction="http://tempuri.org/IService1/GetProductsByIdResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> GetProductsByIdAsync(int[] productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProd", ReplyAction="http://tempuri.org/IService1/DeleteProdResponse")]
        bool DeleteProd(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProd", ReplyAction="http://tempuri.org/IService1/DeleteProdResponse")]
        System.Threading.Tasks.Task<bool> DeleteProdAsync(int P_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        bool DeleteUser(int u_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(int u_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        bool addProduct(string name, string category, string description, double price, int stock, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        System.Threading.Tasks.Task<bool> addProductAsync(string name, string category, string description, double price, int stock, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkProduct", ReplyAction="http://tempuri.org/IService1/checkProductResponse")]
        bool checkProduct(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkProduct", ReplyAction="http://tempuri.org/IService1/checkProductResponse")]
        System.Threading.Tasks.Task<bool> checkProductAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        bool editProduct(string name, string category, string description, double price, int stock, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        System.Threading.Tasks.Task<bool> editProductAsync(string name, string category, string description, double price, int stock, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTotalProdInCart", ReplyAction="http://tempuri.org/IService1/getTotalProdInCartResponse")]
        int getTotalProdInCart(int custId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTotalProdInCart", ReplyAction="http://tempuri.org/IService1/getTotalProdInCartResponse")]
        System.Threading.Tasks.Task<int> getTotalProdInCartAsync(int custId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCartTotals", ReplyAction="http://tempuri.org/IService1/UpdateCartTotalsResponse")]
        void UpdateCartTotals(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCartTotals", ReplyAction="http://tempuri.org/IService1/UpdateCartTotalsResponse")]
        System.Threading.Tasks.Task UpdateCartTotalsAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        void DeleteProduct(int cartProdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int cartProdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/increaseQuantity", ReplyAction="http://tempuri.org/IService1/increaseQuantityResponse")]
        void increaseQuantity(int cartProdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/increaseQuantity", ReplyAction="http://tempuri.org/IService1/increaseQuantityResponse")]
        System.Threading.Tasks.Task increaseQuantityAsync(int cartProdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        void AddToCart(int custId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(int custId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartProds", ReplyAction="http://tempuri.org/IService1/GetCartProdsResponse")]
        Aluwa3.ServiceReference1.TempCartProd[] GetCartProds(int custId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartProds", ReplyAction="http://tempuri.org/IService1/GetCartProdsResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempCartProd[]> GetCartProdsAsync(int custId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductId", ReplyAction="http://tempuri.org/IService1/GetProductIdResponse")]
        int GetProductId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductId", ReplyAction="http://tempuri.org/IService1/GetProductIdResponse")]
        System.Threading.Tasks.Task<int> GetProductIdAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (GetProductByID) of message GetProductByIDRequest does not match the default value (GetProductByID1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByID", ReplyAction="http://tempuri.org/IService1/GetProductByIDResponse")]
        Aluwa3.ServiceReference1.GetProductByIDResponse GetProductByID1(Aluwa3.ServiceReference1.GetProductByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByID", ReplyAction="http://tempuri.org/IService1/GetProductByIDResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.GetProductByIDResponse> GetProductByID1Async(Aluwa3.ServiceReference1.GetProductByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        Aluwa3.ServiceReference1.TempCart GetCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempCart> GetCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderId", ReplyAction="http://tempuri.org/IService1/GetOrderIdResponse")]
        int GetOrderId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderId", ReplyAction="http://tempuri.org/IService1/GetOrderIdResponse")]
        System.Threading.Tasks.Task<int> GetOrderIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProds", ReplyAction="http://tempuri.org/IService1/GetOrderProdsResponse")]
        Aluwa3.ServiceReference1.TempOrderProd[] GetOrderProds(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProds", ReplyAction="http://tempuri.org/IService1/GetOrderProdsResponse")]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempOrderProd[]> GetOrderProdsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkOut", ReplyAction="http://tempuri.org/IService1/checkOutResponse")]
        bool checkOut(int custId, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkOut", ReplyAction="http://tempuri.org/IService1/checkOutResponse")]
        System.Threading.Tasks.Task<bool> checkOutAsync(int custId, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartProductId", ReplyAction="http://tempuri.org/IService1/GetCartProductIdResponse")]
        int GetCartProductId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartProductId", ReplyAction="http://tempuri.org/IService1/GetCartProductIdResponse")]
        System.Threading.Tasks.Task<int> GetCartProductIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetProductByIDRequest() {
        }
        
        public GetProductByIDRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Aluwa3.ServiceReference1.TempProd GetProductByIDResult;
        
        public GetProductByIDResponse() {
        }
        
        public GetProductByIDResponse(Aluwa3.ServiceReference1.TempProd GetProductByIDResult) {
            this.GetProductByIDResult = GetProductByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Aluwa3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Aluwa3.ServiceReference1.IService1>, Aluwa3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aluwa3.ServiceReference1.User Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.User> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public bool Register(Aluwa3.ServiceReference1.User user) {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(Aluwa3.ServiceReference1.User user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public int getCustomerId() {
            return base.Channel.getCustomerId();
        }
        
        public System.Threading.Tasks.Task<int> getCustomerIdAsync() {
            return base.Channel.getCustomerIdAsync();
        }
        
        public Aluwa3.ServiceReference1.User getCustomer(int id) {
            return base.Channel.getCustomer(id);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.User> getCustomerAsync(int id) {
            return base.Channel.getCustomerAsync(id);
        }
        
        public string GetUserType(string email) {
            return base.Channel.GetUserType(email);
        }
        
        public System.Threading.Tasks.Task<string> GetUserTypeAsync(string email) {
            return base.Channel.GetUserTypeAsync(email);
        }
        
        public Aluwa3.ServiceReference1.Product[] getProductByCategory(string category) {
            return base.Channel.getProductByCategory(category);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> getProductByCategoryAsync(string category) {
            return base.Channel.getProductByCategoryAsync(category);
        }
        
        public Aluwa3.ServiceReference1.Product getproductById(int id) {
            return base.Channel.getproductById(id);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product> getproductByIdAsync(int id) {
            return base.Channel.getproductByIdAsync(id);
        }
        
        public Aluwa3.ServiceReference1.Product[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public Aluwa3.ServiceReference1.Product[] GetProductsById(int[] productIds) {
            return base.Channel.GetProductsById(productIds);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.Product[]> GetProductsByIdAsync(int[] productIds) {
            return base.Channel.GetProductsByIdAsync(productIds);
        }
        
        public bool DeleteProd(int P_id) {
            return base.Channel.DeleteProd(P_id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProdAsync(int P_id) {
            return base.Channel.DeleteProdAsync(P_id);
        }
        
        public bool DeleteUser(int u_id) {
            return base.Channel.DeleteUser(u_id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(int u_id) {
            return base.Channel.DeleteUserAsync(u_id);
        }
        
        public bool addProduct(string name, string category, string description, double price, int stock, string image) {
            return base.Channel.addProduct(name, category, description, price, stock, image);
        }
        
        public System.Threading.Tasks.Task<bool> addProductAsync(string name, string category, string description, double price, int stock, string image) {
            return base.Channel.addProductAsync(name, category, description, price, stock, image);
        }
        
        public bool checkProduct(string name) {
            return base.Channel.checkProduct(name);
        }
        
        public System.Threading.Tasks.Task<bool> checkProductAsync(string name) {
            return base.Channel.checkProductAsync(name);
        }
        
        public bool editProduct(string name, string category, string description, double price, int stock, string image) {
            return base.Channel.editProduct(name, category, description, price, stock, image);
        }
        
        public System.Threading.Tasks.Task<bool> editProductAsync(string name, string category, string description, double price, int stock, string image) {
            return base.Channel.editProductAsync(name, category, description, price, stock, image);
        }
        
        public int getTotalProdInCart(int custId) {
            return base.Channel.getTotalProdInCart(custId);
        }
        
        public System.Threading.Tasks.Task<int> getTotalProdInCartAsync(int custId) {
            return base.Channel.getTotalProdInCartAsync(custId);
        }
        
        public void UpdateCartTotals(int cartId) {
            base.Channel.UpdateCartTotals(cartId);
        }
        
        public System.Threading.Tasks.Task UpdateCartTotalsAsync(int cartId) {
            return base.Channel.UpdateCartTotalsAsync(cartId);
        }
        
        public void DeleteProduct(int cartProdId) {
            base.Channel.DeleteProduct(cartProdId);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int cartProdId) {
            return base.Channel.DeleteProductAsync(cartProdId);
        }
        
        public void increaseQuantity(int cartProdId) {
            base.Channel.increaseQuantity(cartProdId);
        }
        
        public System.Threading.Tasks.Task increaseQuantityAsync(int cartProdId) {
            return base.Channel.increaseQuantityAsync(cartProdId);
        }
        
        public void AddToCart(int custId, int prodId) {
            base.Channel.AddToCart(custId, prodId);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(int custId, int prodId) {
            return base.Channel.AddToCartAsync(custId, prodId);
        }
        
        public Aluwa3.ServiceReference1.TempCartProd[] GetCartProds(int custId) {
            return base.Channel.GetCartProds(custId);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempCartProd[]> GetCartProdsAsync(int custId) {
            return base.Channel.GetCartProdsAsync(custId);
        }
        
        public int GetProductId() {
            return base.Channel.GetProductId();
        }
        
        public System.Threading.Tasks.Task<int> GetProductIdAsync() {
            return base.Channel.GetProductIdAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aluwa3.ServiceReference1.GetProductByIDResponse Aluwa3.ServiceReference1.IService1.GetProductByID1(Aluwa3.ServiceReference1.GetProductByIDRequest request) {
            return base.Channel.GetProductByID1(request);
        }
        
        public Aluwa3.ServiceReference1.TempProd GetProductByID1(int id) {
            Aluwa3.ServiceReference1.GetProductByIDRequest inValue = new Aluwa3.ServiceReference1.GetProductByIDRequest();
            inValue.id = id;
            Aluwa3.ServiceReference1.GetProductByIDResponse retVal = ((Aluwa3.ServiceReference1.IService1)(this)).GetProductByID1(inValue);
            return retVal.GetProductByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aluwa3.ServiceReference1.GetProductByIDResponse> Aluwa3.ServiceReference1.IService1.GetProductByID1Async(Aluwa3.ServiceReference1.GetProductByIDRequest request) {
            return base.Channel.GetProductByID1Async(request);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.GetProductByIDResponse> GetProductByID1Async(int id) {
            Aluwa3.ServiceReference1.GetProductByIDRequest inValue = new Aluwa3.ServiceReference1.GetProductByIDRequest();
            inValue.id = id;
            return ((Aluwa3.ServiceReference1.IService1)(this)).GetProductByID1Async(inValue);
        }
        
        public Aluwa3.ServiceReference1.TempCart GetCart() {
            return base.Channel.GetCart();
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempCart> GetCartAsync() {
            return base.Channel.GetCartAsync();
        }
        
        public int GetOrderId() {
            return base.Channel.GetOrderId();
        }
        
        public System.Threading.Tasks.Task<int> GetOrderIdAsync() {
            return base.Channel.GetOrderIdAsync();
        }
        
        public Aluwa3.ServiceReference1.TempOrderProd[] GetOrderProds(int id) {
            return base.Channel.GetOrderProds(id);
        }
        
        public System.Threading.Tasks.Task<Aluwa3.ServiceReference1.TempOrderProd[]> GetOrderProdsAsync(int id) {
            return base.Channel.GetOrderProdsAsync(id);
        }
        
        public bool checkOut(int custId, string address) {
            return base.Channel.checkOut(custId, address);
        }
        
        public System.Threading.Tasks.Task<bool> checkOutAsync(int custId, string address) {
            return base.Channel.checkOutAsync(custId, address);
        }
        
        public int GetCartProductId() {
            return base.Channel.GetCartProductId();
        }
        
        public System.Threading.Tasks.Task<int> GetCartProductIdAsync() {
            return base.Channel.GetCartProductIdAsync();
        }
    }
}
